version: "3.8"


networks:
  db:

volumes:
  postgres_data:

services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: convert
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: convert
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - db
    depends_on:
      - db
    

  front:
    container_name: converter_client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 9000:80
    depends_on:
      - server